#!/usr/bin/env python3

import sys
import requests
import re
from bs4 import BeautifulSoup

BASE_URL = "https://genius.com/"

def main():
    if len(sys.argv) < 3:
        if len(sys.argv) < 2:
            help(1)
        else:
            if sys.argv[1] == "-h" or sys.argv[1] == "--help":
                help(0)
            else:
                help(1)

    url = get_url()
    soup = get_soup(url)

    lyrics_soup = soup.find_all("div", attrs={"class": "Lyrics-sc-1bcc94c6-1 bzTABU"})
    if lyrics_soup == []:
        placeholder = soup.find("div", attrs={"class": "LyricsPlaceholder-sc-99de6a4b-2 kyAbuL"})
        if placeholder == None:
            print("Error: song not found.")
            sys.exit(1)
        print(placeholder.text)
        sys.exit(0)

    lyrics = ""

    for l in lyrics_soup:
        lyrics += l.get_text(separator="\n", strip=True)
        lyrics += "\n"

    lyrics = re.sub(r"(\[.*\])", r"\n\033[31m\1\033[0m", lyrics)
    print(lyrics.strip())

def get_soup(url):
    try:
        r = requests.get(url)
    except ValueError:
        print(f"Error: could not download webpage {url}.")
        sys.exit(1)

    try:
        soup = BeautifulSoup(r.text, "html.parser")
    except ValueError:
        print("Error: could not parse BeautifulSoup.")
        sys.exit(1)

    return soup

def get_url():
    url = BASE_URL + sys.argv[1]
    for i in range(2, len(sys.argv)):
        word = sys.argv[i].strip()

        if word == "-":
            continue

        word = word.replace("&", "and")

        while word.startswith("_"):
            word = word[1:]
        while word.endswith("_"):
            word = word[:-1]
        word = word.replace("_", "-")

        word = re.sub(r"[^a-zA-Z0-9-]", "", word)
            
        if word == "":
            continue

        url += f"-{word}"

    url += "-lyrics"
    return url

def help(exit_code):
    print("usage: lyricli <artist> <song>")
    sys.exit(exit_code)

main()
